# Generated by Django 6.0.3 on 2026-03-28 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.UUIDField(db_index=True)),
                ('message_id', models.CharField(db_index=True, max_length=64)),
                ('flagged_session_id', models.CharField(db_index=True, max_length=64)),
                ('flagged_username', models.CharField(max_length=30)),
                ('reporter_session_id', models.CharField(max_length=64)),
                ('reporter_username', models.CharField(max_length=30)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('hate_speech', 'Hate Speech'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'message_flags',
                'indexes': [models.Index(fields=['room_id', 'flagged_session_id'], name='message_fla_room_id_aeba07_idx')],
                'constraints': [models.UniqueConstraint(fields=('message_id', 'reporter_session_id'), name='unique_flag_per_reporter_per_message')],
            },
        ),
    ]
