# Generated by Django 6.0.3 on 2026-03-28 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('topic_tag', models.CharField(blank=True, max_length=30)),
                ('creator_id', models.UUIDField(db_index=True)),
                ('creator_username', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('invite', 'Invite Only')], default='public', max_length=10)),
                ('invite_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('radius_km', models.FloatField(choices=[(0.5, '500m'), (1.0, '1km'), (2.0, '2km'), (5.0, '5km')], default=2.0)),
                ('timer_minutes', models.IntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (180, '3 hours'), (360, '6 hours')], default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_empty_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='rooms_is_acti_bc1f7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('username', models.CharField(max_length=30)),
                ('role', models.CharField(default='guest', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.room')),
            ],
            options={
                'db_table': 'room_memberships',
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(max_length=30)),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='rooms.room')),
            ],
            options={
                'db_table': 'waitlist_entries',
                'ordering': ['queued_at'],
            },
        ),
    ]
